image: python:3.11
stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - pip install --upgrade pip
  - pip install numpy pandas scikit-learn matplotlib seaborn papermill nbval pytest

test_notebook:
  stage: test
  script:
    - pytest --nbval facial_emotional_recognition.ipynb
    - python -c "import nbformat; import ast; nb = nbformat.read('facial_emotional_recognition.ipynb', as_version=4); print('Notebook validation passed')"
  only:
    changes:
      - "facial_emotional_recognition.ipynb"
      - "requirements.txt"